package de.florianmichael.viabeta.protocol.protocol1_4_2to1_3_1_2.rewriter;

import de.florianmichael.viabeta.api.rewriter.LegacySoundRewriter;
import de.florianmichael.viabeta.protocol.protocol1_4_2to1_3_1_2.ClientboundPackets1_3_1;
import de.florianmichael.viabeta.protocol.protocol1_4_2to1_3_1_2.Protocol1_4_2to1_3_1_2;

public class SoundRewriter extends LegacySoundRewriter<Protocol1_4_2to1_3_1_2> {

    public SoundRewriter(Protocol1_4_2to1_3_1_2 protocol) {
        super(protocol, "1.3.2", 121);

        addSoundMapping("ambient.cave.cave", "ambient.cave.cave");
        addSoundMapping("ambient.weather.rain", "ambient.weather.rain");
        addSoundMapping("ambient.weather.thunder", "ambient.weather.thunder");
        addSoundMapping("damage.fallbig", "damage.fallbig");
        addSoundMapping("damage.fallsmall", "damage.fallsmall");
        addSoundMapping("damage.hurtflesh", "damage.hit");
        addSoundMapping("fire.fire", "fire.fire");
        addSoundMapping("fire.ignite", "fire.ignite");
        addSoundMapping("liquid.lava", "liquid.lava");
        addSoundMapping("liquid.lavapop", "liquid.lavapop");
        addSoundMapping("liquid.splash", "liquid.splash");
        addSoundMapping("liquid.water", "liquid.water");
        addSoundMapping("mob.blaze.breathe", "mob.blaze.breathe");
        addSoundMapping("mob.blaze.death", "mob.blaze.death");
        addSoundMapping("mob.blaze.hit", "mob.blaze.hit");
        addSoundMapping("mob.cat.hiss", "mob.cat.hiss");
        addSoundMapping("mob.cat.hitt", "mob.cat.hitt");
        addSoundMapping("mob.cat.meow", "mob.cat.meow");
        addSoundMapping("mob.cat.purr", "mob.cat.purr");
        addSoundMapping("mob.cat.purreow", "mob.cat.purreow");
        addSoundMapping("mob.chicken", "mob.chicken.say");
        addSoundMapping("mob.chickenhurt", "mob.chicken.hurt");
        addSoundMapping("mob.chickenplop", "mob.chicken.plop");
        addSoundMapping("mob.cow", "mob.cow.say");
        addSoundMapping("mob.cowhurt", "mob.cow.hurt");
        addSoundMapping("mob.creeper", "mob.creeper.say");
        addSoundMapping("mob.creeperdeath", "mob.creeper.death");
        addSoundMapping("mob.endermen.death", "mob.endermen.death");
        addSoundMapping("mob.endermen.hit", "mob.endermen.hit");
        addSoundMapping("mob.endermen.idle", "mob.endermen.idle");
        addSoundMapping("mob.endermen.portal", "mob.endermen.portal");
        addSoundMapping("mob.endermen.scream", "mob.endermen.scream");
        addSoundMapping("mob.endermen.stare", "mob.endermen.stare");
        addSoundMapping("mob.ghast.affectionate scream", "mob.ghast.affectionate_scream");
        addSoundMapping("mob.ghast.charge", "mob.ghast.charge");
        addSoundMapping("mob.ghast.death", "mob.ghast.death");
        addSoundMapping("mob.ghast.fireball", "mob.ghast.fireball");
        addSoundMapping("mob.ghast.moan", "mob.ghast.moan");
        addSoundMapping("mob.ghast.scream", "mob.ghast.scream");
        addSoundMapping("mob.irongolem.death", "mob.irongolem.death");
        addSoundMapping("mob.irongolem.hit", "mob.irongolem.hit");
        addSoundMapping("mob.irongolem.throw", "mob.irongolem.throw");
        addSoundMapping("mob.irongolem.walk", "mob.irongolem.walk");
        addSoundMapping("mob.magmacube.big", "mob.magmacube.big");
        addSoundMapping("mob.magmacube.jump", "mob.magmacube.jump");
        addSoundMapping("mob.magmacube.small", "mob.magmacube.small");
        addSoundMapping("mob.pig", "mob.pig.say");
        addSoundMapping("mob.pigdeath", "mob.pig.death");
        addSoundMapping("mob.sheep", "mob.sheep.say");
        addSoundMapping("mob.silverfish.hit", "mob.silverfish.hit");
        addSoundMapping("mob.silverfish.kill", "mob.silverfish.kill");
        addSoundMapping("mob.silverfish.say", "mob.silverfish.say");
        addSoundMapping("mob.silverfish.step", "mob.silverfish.step");
        addSoundMapping("mob.skeleton", "mob.skeleton.say");
        addSoundMapping("mob.skeletondeath", "mob.skeleton.death");
        addSoundMapping("mob.skeletonhurt", "mob.skeleton.hurt");
        addSoundMapping("mob.slime", "mob.slime.small");
        addSoundMapping("mob.slimeattack", "mob.slime.attack");
        addSoundMapping("mob.spider", "mob.spider.say");
        addSoundMapping("mob.spiderdeath", "mob.spider.death");
        addSoundMapping("mob.wolf.bark", "mob.wolf.bark");
        addSoundMapping("mob.wolf.death", "mob.wolf.death");
        addSoundMapping("mob.wolf.growl", "mob.wolf.growl");
        addSoundMapping("mob.wolf.howl", "mob.wolf.howl");
        addSoundMapping("mob.wolf.hurt", "mob.wolf.hurt");
        addSoundMapping("mob.wolf.panting", "mob.wolf.panting");
        addSoundMapping("mob.wolf.shake", "mob.wolf.shake");
        addSoundMapping("mob.wolf.whine", "mob.wolf.whine");
        addSoundMapping("mob.zombie.metal", "mob.zombie.metal");
        addSoundMapping("mob.zombie", "mob.zombie.say");
        addSoundMapping("mob.zombie.wood", "mob.zombie.wood");
        addSoundMapping("mob.zombie.woodbreak", "mob.zombie.woodbreak");
        addSoundMapping("mob.zombiedeath", "mob.zombie.death");
        addSoundMapping("mob.zombiehurt", "mob.zombie.hurt");
        addSoundMapping("mob.zombiepig.zpig", "mob.zombiepig.zpig");
        addSoundMapping("mob.zombiepig.zpigangry", "mob.zombiepig.zpigangry");
        addSoundMapping("mob.zombiepig.zpigdeath", "mob.zombiepig.zpigdeath");
        addSoundMapping("mob.zombiepig.zpighurt", "mob.zombiepig.zpighurt");
        addSoundMapping("mob.villager.default", "mob.villager.default");
        addSoundMapping("mob.villager.defaulthurt", "mob.villager.defaulthurt");
        addSoundMapping("mob.villager.defaultdeath", "mob.villager.defaultdeath");
        addSoundMapping("note.bass", "note.bass");
        addSoundMapping("note.bassattack", "note.bassattack");
        addSoundMapping("note.bd", "note.bd");
        addSoundMapping("note.harp", "note.harp");
        addSoundMapping("note.hat", "note.hat");
        addSoundMapping("note.pling", "note.pling");
        addSoundMapping("note.snare", "note.snare");
        addSoundMapping("portal.portal", "portal.portal");
        addSoundMapping("portal.travel", "portal.travel");
        addSoundMapping("portal.trigger", "portal.trigger");
        addSoundMapping("random.bow", "random.bow");
        addSoundMapping("random.bowhit", "random.bowhit");
        addSoundMapping("random.break", "random.break");
        addSoundMapping("random.breath", "random.breath");
        addSoundMapping("random.burp", "random.burp");
        addSoundMapping("random.chestclosed", "random.chestclosed");
        addSoundMapping("random.chestopen", "random.chestopen");
        addSoundMapping("random.click", "random.click");
        addSoundMapping("random.door_close", "random.door_close");
        addSoundMapping("random.door_open", "random.door_open");
        addSoundMapping("random.drink", "random.drink");
        addSoundMapping("random.drr", "");
        addSoundMapping("random.eat", "random.eat");
        addSoundMapping("random.explode", "random.explode");
        addSoundMapping("random.fizz", "random.fizz");
        addSoundMapping("random.fuse", "random.fuse");
        addSoundMapping("random.glass", "random.glass");
        addSoundMapping("random.hurt", "damage.hit");
        addSoundMapping("random.levelup", "random.levelup");
        addSoundMapping("random.old_explode", "random.explode");
        addSoundMapping("random.orb", "random.orb");
        addSoundMapping("random.pop", "random.pop");
        addSoundMapping("random.splash", "random.splash");
        addSoundMapping("random.wood click", "random.wood_click");
        addSoundMapping("step.cloth", "step.cloth");
        addSoundMapping("step.grass", "step.grass");
        addSoundMapping("step.gravel", "step.gravel");
        addSoundMapping("step.sand", "step.sand");
        addSoundMapping("step.snow", "step.snow");
        addSoundMapping("step.stone", "step.stone");
        addSoundMapping("step.wood", "step.wood");
        addSoundMapping("tile.piston.in", "tile.piston.in");
        addSoundMapping("tile.piston.out", "tile.piston.out");
    }

    @Override
    protected void registerPackets() {
        super.registerPackets();

        this.registerNamedSound_1_6_4(ClientboundPackets1_3_1.NAMED_SOUND);
    }
}
